### ISSUE TITLE
unable to install dependency packages

### ISSUE THREAD

**Issue by hemachowdary** [codeforequity-at/testmybot-sample-calculator#1]
Hi I am trying to use this sample to demonstrate the chatbot testing using node "testmybot" package. When I execute "npm install" command I am getting error. Please find the screenshot of the same attached below. 
![error](https://user-images.githubusercontent.com/2978192/36463681-7e02a740-16f1-11e8-86fa-0cbeaf49cb4c.JPG)
Steps that I have followed: 
1. Downloaded the project from [https://github.com/codeforequity-at/testmybot-sample-calculator]
2. Extracted the project to "testmybot-sample-calculator-master" folder
3. Inside the folder executed "npm install" command
4. After installing some packages, looks like while installing botkit package it is throwing error 
Please let me know if I have missed out any steps.

**Comment by ujja** [comment]
Python is not found.

Please create/update PYTHON env variable, install python, or install https://www.npmjs.com/package/windows-build-tools.
